site_name: ConnOSS Metadata Schema
site_url:  https://connoss-project.github.io/vocab/
repo_url: https://github.com/ConnOSS-Project/vocab
repo_name: vocab
nav:
    - Home: index.md
    - Types:
      - Overview: 'Types/index.md'
      - Software Type: 'Types/software-type.md'
    - Profiles:
      - 'Profiles/index.md'
      - 'Profiles/Software.md'
      
theme:
  name: material
  language: en
  logo: connoss_logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    scheme: default
    primary: teal
    accent: teal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search
