site_name: ConnOSS Metadata Schema
site_url:  https://connoss-project.github.io/vocab/
repo_url: https://github.com/ConnOSS-Project/vocab
repo_name: vocab
nav:
    - Home: index.md
    - Types:
      - Overview: 'Types/index.md'
      - 'Types/Software.md'
      - 'Types/TestAction.md'
    - Profiles:
      - Overview: 'Profiles/index.md'
      - 'Profiles/Software.md'
      
theme:
  name: material
  language: en
  logo: logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    scheme: default
    primary: teal
    accent: teal

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search
  - redirects:
      redirect_maps:
        'terms/Software.md': 'Types/Software.md'
        'terms/TestAction.md': 'Types/TestAction.md'
        'terms/acknowledgements.md': 'Properties/acknowledgements.md'
        'terms/developerDocumentation.md': 'Properties/developerDocumentation.md'
        'terms/documentation.md': 'Properties/documentation.md'
        'terms/implementsSpecification.md': 'Properties/implementsSpecification.md'
        'terms/input.md': 'Properties/input.md'
        'terms/output.md': 'Properties/partOfCommunity.md'
        'terms/partOfCommunity.md': 'Properties/partOfCommunity.md'
        'terms/researchDomain.md': 'Properties/researchDomain.md'
        'terms/softwareContainer.md': 'Properties/softwareContainer.md'
        'terms/softwareInterface.md': 'Properties/softwareInterface.md'
        'terms/testingAction.md': 'Properties/testingAction.md'
        'terms/testType.md': 'Properties/testType.md'
        'terms/userDocumentation.md': 'Properties/userDocumentation.md'


extra_css:
  - stylesheets/extra.css

hooks:
  - code/copy_schema.py

validation:
  nav:
    omitted_files: ignore
